import {expect,test} from "@playwright/test";
import {unlock,selectDraft,navigate} from "./helpers";
for(const width of [1440,1280,390])test(`unified account directory at ${width}`,async({page})=>{
  await page.setViewportSize({width,height:width===390?844:900});
  await unlock(page);await selectDraft(page);await navigate(page,"账号池");
  for(const name of ["API","Codex / ChatGPT","Claude","Kimi","Kiro","Grok"])await expect(page.getByRole("region",{name:`${name} 账号`,exact:true})).toBeVisible();
  await expect(page.getByText("alex@example.test",{exact:true})).toBeVisible();
  await page.getByLabel("搜索账号",{exact:true}).fill("alex@example.test");
  await expect(page.locator(".account-list tbody tr")).toHaveCount(1);
  await page.getByRole("button",{name:/Responses.*个已配置连接/u}).click();
  await expect(page.getByRole("dialog",{name:"接口连接"})).toContainText("不同接口可以支持不同请求格式");
  await expect(page.getByRole("link",{name:"管理接口连接",exact:true})).toBeVisible();
  await page.keyboard.press("Escape");
  await page.getByLabel("搜索账号",{exact:true}).fill("");
  await page.getByRole("button",{name:"添加账号",exact:true}).click();
  const dialog=page.getByRole("dialog",{name:"添加账号",exact:true});
  await dialog.getByLabel("渠道",{exact:true}).selectOption("grok.build");
  await dialog.getByLabel("账号名称").fill("autoreg-test-batch");
  const claims=Buffer.from(JSON.stringify({email:"build.member@example.test",sub:"fixture-subject",exp:Math.floor(Date.now()/1000)+3600})).toString("base64url");
  await dialog.locator("textarea").fill(JSON.stringify({access_token:`header.${claims}.signature`,refresh_token:"fixture-refresh",expires_at:new Date(Date.now()+3600000).toISOString()}));
  await dialog.getByRole("button",{name:"添加账号",exact:true}).click();
  await expect(dialog).toHaveCount(0);
  const grok=page.getByRole("region",{name:"Grok 账号",exact:true});
  await expect(grok.getByText("build.member@example.test",{exact:true})).toBeVisible();
  await expect(grok).toContainText("来源 · Autoreg");
  await expect(page.locator("main")).not.toContainText("autoreg-test-batch");
  await expect(grok.locator(".account-list tbody tr")).toHaveCount(1);
  await expect(page.locator(".sheet-ghost")).toHaveCount(0);
  const geometry=await page.locator(".account-directory-head").first().evaluate((e)=>{
    const h=e.querySelector("h3")!;return {padding:getComputedStyle(e).padding,head:e.getBoundingClientRect().x,title:h.getBoundingClientRect().x,margin:getComputedStyle(h).margin,display:getComputedStyle(e).display};
  });
  expect(geometry.title-geometry.head).toBeGreaterThanOrEqual(16);
  await page.screenshot({path:`../../output/accounts-directory-${width}.png`,fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test("account directory retains dark and accessibility preferences",async({page})=>{
  await page.emulateMedia({colorScheme:"dark",reducedMotion:"reduce",contrast:"more"});
  await page.setViewportSize({width:1280,height:720});
  await unlock(page);await selectDraft(page);await navigate(page,"账号池");
  await expect(page.getByText("alex@example.test",{exact:true})).toBeVisible();
  const filter=page.getByRole("navigation",{name:"账号类别"}).getByRole("button",{name:"Codex / ChatGPT",exact:true});
  await filter.focus();await page.keyboard.press("Enter");
  await expect(filter).toHaveAttribute("aria-pressed","true");
  await expect(page.locator(".account-group")).toHaveCount(1);
  await page.screenshot({path:"../../output/accounts-directory-dark.png",fullPage:true});
});
