import { expect, test } from "@playwright/test";
import { unlock, navigate, selectVersion } from "./helpers";

test("serving model contexts stay separate and source links preserve exact IDs", async ({ page }) => {
  await unlock(page);
  await selectVersion(page, "v-2026-07");
  await navigate(page, "模型目录");
  await page.getByText("检查客户端可用模型", {exact:true}).click();
  const panel = page.getByRole("region", { name: "授权有效模型" });
  await panel.getByLabel("模型授权身份").selectOption("team-default");
  await expect(panel).toContainText("exact-alpha");
  await panel.getByLabel("模型授权身份").selectOption("team-batch");
  await expect(panel).toContainText("exact-beta");
  await expect(panel).not.toContainText("exact-alpha");
  await panel.getByRole("button", { name: "模型来源" }).click();
  const inspector = page.getByRole("dialog");
  await expect(inspector.locator('[data-resource-id="endpoint-exact-beta"]')).toBeVisible();
  await expect(inspector).toContainText("目录 v7");
  await expect(inspector).toContainText("硬过期");
  await expect(inspector).toContainText("目录准入有效");
  await inspector.getByRole("link", { name: "在诊断中检查该模型" }).click();
  await expect(page.getByLabel("请求模型", { exact: true })).toHaveValue("exact-beta");
  await navigate(page, "模型目录");
  await page.getByText("检查客户端可用模型", {exact:true}).click();
  await panel.getByLabel("模型授权上下文类型").selectOption("client_key_id");
  await panel.getByLabel("模型授权身份").selectOption("key-cli");
  await expect(panel).toContainText("exact-alpha");
  await panel.getByLabel("模型授权身份").selectOption("key-dead");
  await expect(panel.getByRole("alert")).toBeVisible();
  await expect(panel).not.toContainText("exact-alpha");
});

test("an authorized model survives draft selection and seeds a new route candidate", async ({ page }) => {
  await unlock(page);
  await selectVersion(page, "v-2026-07");
  await navigate(page, "模型目录");
  await page.getByText("检查客户端可用模型", {exact:true}).click();
  await page.getByLabel("模型授权身份").selectOption("team-default");
  await page.getByRole("button", { name: "模型来源" }).click();
  await page.getByRole("link", { name: "用于草稿候选" }).click();
  const handoff = page.getByRole("region", { name: "待用于草稿的模型" });
  await expect(handoff).toContainText("exact-alpha");
  await navigate(page, "配置版本");
  await page.locator('[data-version-id="draft-2026-08"]').getByRole("button", { name: "编辑草稿" }).click();
  await expect(page.locator("main.canvas")).toHaveAttribute("data-context-version", "draft-2026-08");
  await page.goBack();
  await page.goBack();
  await expect(handoff).toContainText("exact-alpha");
  await handoff.getByRole("button", { name: "开放此模型" }).click();
  const dialog = page.getByRole("dialog", { name: "接入模型" });
  await expect(dialog.getByRole("textbox", { name: "上游模型 ID" })).toHaveValue("exact-alpha");
  await expect(dialog.getByRole("combobox", { name: "接口连接" })).toHaveValue("");
  await dialog.getByRole("combobox", { name: "接口连接" }).selectOption("ep-relay-a-responses");
  await dialog.getByRole("button", { name: "保存并应用" }).click();
  await expect(page.getByRole("dialog", { name: "模型接入结果" })).toContainText("已保存到当前草稿");
  await page.getByRole("dialog", { name: "模型接入结果" }).getByRole("button", { name: "核对配置" }).click();
  const candidates=await page.evaluate(async()=>{
    const {call}=await import("/src/api/client.ts");
    return call<{items:readonly {upstream_model:string;endpoint_id:string}[]}>("listRouteCandidates",{query:{limit:100}},{versionScoped:true});
  });
  expect(candidates.items.some(row=>row.upstream_model==="exact-alpha"&&row.endpoint_id==="ep-relay-a-responses")).toBe(true);
  await handoff.getByRole("button", { name: "清除模型选择" }).click();
  await expect(handoff).toHaveCount(0);
});
