[package]
name = "gateway-stream"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
gateway-core = { path = "../gateway-core" }
gateway-protocol = { path = "../gateway-protocol" }

[lints]
workspace = true
